const KNOWN_CELL_COLOR = "#FFFFFF";
const UNKNOWN_CELL_VALUE = "(不明)";
const UNKNOWN_CELL_COLOR = "#808080";

const ROW_INDEX_TO_READ_VALUE = 2;
const COLUMN_INDEX_TO_READ_VALUE = 3;

const ROW_INDEX_OF_BASE_OF_PLAYERS = 4;
